-- =============================================
-- Reporting Service Database Schema
-- Generated from code analysis
-- =============================================

-- Create main reporting database
CREATE DATABASE [ReportingService]
GO

USE [ReportingService]
GO

-- =============================================
-- Core Reporting Tables
-- =============================================

-- Report Definitions Table
CREATE TABLE [dbo].[REPORTS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [NAME] NVARCHAR(100) NOT NULL,
    [FILENAME] NVARCHAR(255) NOT NULL,
    [DESCRIPTION] NVARCHAR(500) NULL,
    [SQL_REP] NTEXT NULL,
    [DMS_FLAG] CHAR(1) NULL DEFAULT 'N',
    [DT_FLAG] CHAR(1) NULL DEFAULT 'N',
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1
)
GO

-- Report Entities Table (Report-Organization relationships)
CREATE TABLE [dbo].[REPORT_ENTITIES] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [REPORT_ID] NVARCHAR(15) NOT NULL,
    [OU_ID] NVARCHAR(15) NULL,
    [CON_ID] NVARCHAR(15) NULL,
    [PRI_LST_ID] NVARCHAR(15) NULL,
    [REP_DEST_ID] NVARCHAR(15) NULL,
    [FORMAT] NVARCHAR(50) NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1,
    FOREIGN KEY ([REPORT_ID]) REFERENCES [dbo].[REPORTS]([ROW_ID])
)
GO

-- Report Execution Schedule Table
CREATE TABLE [dbo].[REPORT_EXECUTION_SCHEDULE] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [TRAN_ID] NVARCHAR(50) NOT NULL,
    [ENT_ID] NVARCHAR(15) NOT NULL,
    [EXEC_CON_ID] NVARCHAR(15) NULL,
    [REP_DEST_ID] NVARCHAR(15) NULL,
    [FORMAT] NVARCHAR(50) NULL,
    [STORE_PATH] NVARCHAR(500) NULL,
    [PORTAL_FLG] CHAR(1) NULL DEFAULT 'N',
    [ADDL_DESC] NVARCHAR(500) NULL,
    [STATUS] NVARCHAR(50) NULL DEFAULT 'PENDING',
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1,
    FOREIGN KEY ([ENT_ID]) REFERENCES [dbo].[REPORT_ENTITIES]([ROW_ID])
)
GO

-- Report Destinations Table
CREATE TABLE [dbo].[REPORT_DESTINATIONS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [NAME] NVARCHAR(100) NOT NULL,
    [TYPE_CD] NVARCHAR(50) NOT NULL,
    [HOSTNAME] NVARCHAR(255) NULL,
    [OUTPUT_PATH] NVARCHAR(500) NULL,
    [USERNAME] NVARCHAR(100) NULL,
    [PASSWORD] NVARCHAR(100) NULL,
    [SAVE_TO_DOC] CHAR(1) NULL DEFAULT 'N',
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1
)
GO

-- =============================================
-- Contact and Organization Tables
-- =============================================

-- Contacts Table
CREATE TABLE [dbo].[CONTACTS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [FST_NAME] NVARCHAR(50) NULL,
    [LAST_NAME] NVARCHAR(50) NULL,
    [EMAIL_ADDR] NVARCHAR(100) NULL,
    [X_REGISTRATION_NUM] NVARCHAR(50) NULL,
    [PR_DEPT_OU_ID] NVARCHAR(15) NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1
)
GO

-- Organizations Table
CREATE TABLE [dbo].[ORGANIZATIONS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [NAME] NVARCHAR(100) NOT NULL,
    [PR_SHIP_PER_ID] NVARCHAR(15) NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1,
    FOREIGN KEY ([PR_SHIP_PER_ID]) REFERENCES [dbo].[CONTACTS]([ROW_ID])
)
GO

-- =============================================
-- Subscription and List Management Tables
-- =============================================

-- Primary Lists Table
CREATE TABLE [dbo].[PRIMARY_LISTS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [NAME] NVARCHAR(100) NOT NULL,
    [X_CONTRACT_ACCNT_ID] NVARCHAR(15) NULL,
    [X_CONTRACT_CNTCT_ID] NVARCHAR(15) NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1,
    FOREIGN KEY ([X_CONTRACT_CNTCT_ID]) REFERENCES [dbo].[CONTACTS]([ROW_ID])
)
GO

-- Subscriptions Table
CREATE TABLE [dbo].[SUBSCRIPTIONS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [NAME] NVARCHAR(100) NOT NULL,
    [DOMAIN] NVARCHAR(100) NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1
)
GO

-- Contact Subscriptions Junction Table
CREATE TABLE [dbo].[CONTACT_SUBSCRIPTIONS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [CON_ID] NVARCHAR(15) NOT NULL,
    [SUB_ID] NVARCHAR(15) NOT NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1,
    FOREIGN KEY ([CON_ID]) REFERENCES [dbo].[CONTACTS]([ROW_ID]),
    FOREIGN KEY ([SUB_ID]) REFERENCES [dbo].[SUBSCRIPTIONS]([ROW_ID])
)
GO

-- =============================================
-- Session and Training Tables
-- =============================================

-- Sessions Table
CREATE TABLE [dbo].[SESSIONS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [NAME] NVARCHAR(100) NOT NULL,
    [SESSION_DATE] DATETIME NULL,
    [TRAINER_ID] NVARCHAR(15) NULL,
    [CO_TRAINER_ID] NVARCHAR(15) NULL,
    [WORKSHOP_ID] NVARCHAR(15) NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1,
    FOREIGN KEY ([TRAINER_ID]) REFERENCES [dbo].[CONTACTS]([ROW_ID]),
    FOREIGN KEY ([CO_TRAINER_ID]) REFERENCES [dbo].[CONTACTS]([ROW_ID])
)
GO

-- Session Participants Table
CREATE TABLE [dbo].[SESSION_PARTICIPANTS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [SESSION_ID] NVARCHAR(15) NOT NULL,
    [PARTICIPANT_ID] NVARCHAR(15) NOT NULL,
    [STATUS] NVARCHAR(50) NULL DEFAULT 'REGISTERED',
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1,
    FOREIGN KEY ([SESSION_ID]) REFERENCES [dbo].[SESSIONS]([ROW_ID]),
    FOREIGN KEY ([PARTICIPANT_ID]) REFERENCES [dbo].[CONTACTS]([ROW_ID])
)
GO

-- =============================================
-- Configuration and Lookup Tables
-- =============================================

-- List of Values Table
CREATE TABLE [dbo].[LIST_OF_VALUES] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [TYPE] NVARCHAR(50) NOT NULL,
    [VAL] NVARCHAR(100) NOT NULL,
    [DISP_VAL] NVARCHAR(100) NULL,
    [ACTIVE_FLG] CHAR(1) NULL DEFAULT 'Y',
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1
)
GO

-- Sub Screens Table
CREATE TABLE [dbo].[SUB_SCREENS] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [NAME] NVARCHAR(100) NOT NULL,
    [KEY_FIELD] NVARCHAR(100) NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1
)
GO

-- =============================================
-- Document Management Tables
-- =============================================

-- Document Management System Table
CREATE TABLE [dbo].[DOCUMENT_MANAGEMENT] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [DOCUMENT_NAME] NVARCHAR(255) NOT NULL,
    [DOCUMENT_PATH] NVARCHAR(500) NULL,
    [DOCUMENT_TYPE] NVARCHAR(50) NULL,
    [FILE_SIZE] BIGINT NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1
)
GO

-- =============================================
-- Processing and Queue Tables
-- =============================================

-- Processing Queue Table
CREATE TABLE [dbo].[PROCESSING_QUEUE] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [PROCESS_TYPE] NVARCHAR(50) NOT NULL,
    [PROCESS_DATA] NTEXT NULL,
    [STATUS] NVARCHAR(50) NULL DEFAULT 'PENDING',
    [PRIORITY] INT NULL DEFAULT 5,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1
)
GO

-- =============================================
-- Audit and History Tables
-- =============================================

-- Letter History Table
CREATE TABLE [dbo].[LETTER_HISTORY] (
    [ROW_ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [LETTER_TYPE] NVARCHAR(50) NULL,
    [RECIPIENT_ID] NVARCHAR(15) NULL,
    [SENT_DATE] DATETIME NULL,
    [STATUS] NVARCHAR(50) NULL,
    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(15) NULL,
    [LAST_UPD] DATETIME NOT NULL DEFAULT GETDATE(),
    [LAST_UPD_BY] NVARCHAR(15) NULL,
    [MODIFICATION_NUM] INT NOT NULL DEFAULT 1,
    FOREIGN KEY ([RECIPIENT_ID]) REFERENCES [dbo].[CONTACTS]([ROW_ID])
)
GO

-- =============================================
-- Test and Development Tables
-- =============================================

-- Test Reporter Table
CREATE TABLE [dbo].[TEST_REPORTER] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [TEST_NAME] NVARCHAR(100) NULL,
    [TEST_DATA] NVARCHAR(500) NULL,
    [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE()
)
GO

-- =============================================
-- Indexes for Performance
-- =============================================

-- Indexes on frequently queried columns
CREATE INDEX IX_REPORTS_NAME ON [dbo].[REPORTS] ([NAME])
GO

CREATE INDEX IX_REPORT_ENTITIES_REPORT_ID ON [dbo].[REPORT_ENTITIES] ([REPORT_ID])
GO

CREATE INDEX IX_REPORT_ENTITIES_OU_ID ON [dbo].[REPORT_ENTITIES] ([OU_ID])
GO

CREATE INDEX IX_REPORT_EXECUTION_SCHEDULE_TRAN_ID ON [dbo].[REPORT_EXECUTION_SCHEDULE] ([TRAN_ID])
GO

CREATE INDEX IX_REPORT_EXECUTION_SCHEDULE_STATUS ON [dbo].[REPORT_EXECUTION_SCHEDULE] ([STATUS])
GO

CREATE INDEX IX_CONTACTS_EMAIL ON [dbo].[CONTACTS] ([EMAIL_ADDR])
GO

CREATE INDEX IX_CONTACTS_REGISTRATION_NUM ON [dbo].[CONTACTS] ([X_REGISTRATION_NUM])
GO

CREATE INDEX IX_SESSIONS_DATE ON [dbo].[SESSIONS] ([SESSION_DATE])
GO

CREATE INDEX IX_SESSION_PARTICIPANTS_SESSION_ID ON [dbo].[SESSION_PARTICIPANTS] ([SESSION_ID])
GO

CREATE INDEX IX_LIST_OF_VALUES_TYPE ON [dbo].[LIST_OF_VALUES] ([TYPE])
GO

CREATE INDEX IX_PROCESSING_QUEUE_STATUS ON [dbo].[PROCESSING_QUEUE] ([STATUS])
GO

-- =============================================
-- Sample Data Insertion
-- =============================================

-- Insert sample report formats
INSERT INTO [dbo].[LIST_OF_VALUES] ([ROW_ID], [TYPE], [VAL], [DISP_VAL]) VALUES
('RPT_FMT_001', 'REPORT_FORMATS', 'PDF', 'PDF Document'),
('RPT_FMT_002', 'REPORT_FORMATS', 'XLS', 'Excel Spreadsheet'),
('RPT_FMT_003', 'REPORT_FORMATS', 'DOC', 'Word Document'),
('RPT_FMT_004', 'REPORT_FORMATS', 'CSV', 'Comma Separated Values'),
('RPT_FMT_005', 'REPORT_FORMATS', 'XML', 'XML Document')
GO

-- Insert sample report destinations
INSERT INTO [dbo].[REPORT_DESTINATIONS] ([ROW_ID], [NAME], [TYPE_CD], [HOSTNAME], [OUTPUT_PATH]) VALUES
('DEST_001', 'Email', 'EMAIL', NULL, NULL),
('DEST_002', 'File System', 'FILE', NULL, 'C:\Reports\Output\'),
('DEST_003', 'FTP Server', 'FTP', 'ftp.company.com', '/reports/'),
('DEST_004', 'Portal', 'PORTAL', NULL, NULL)
GO

-- Insert sample report
INSERT INTO [dbo].[REPORTS] ([ROW_ID], [NAME], [FILENAME], [DESCRIPTION], [SQL_REP]) VALUES
('RPT_001', 'Sample Report', 'SampleReport.rpt', 'A sample Crystal Report', 'SELECT * FROM CONTACTS WHERE ACTIVE = 1')
GO

-- Insert sample report entity
INSERT INTO [dbo].[REPORT_ENTITIES] ([ROW_ID], [REPORT_ID], [REP_DEST_ID], [FORMAT]) VALUES
('ENT_001', 'RPT_001', 'DEST_001', 'PDF')
GO

-- =============================================
-- Stored Procedures
-- =============================================

-- Procedure to get report execution status
CREATE PROCEDURE [dbo].[GetReportStatus]
    @TranId NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    
    SELECT 
        RES.STATUS,
        RES.CREATED,
        RES.LAST_UPD,
        R.NAME AS REPORT_NAME,
        RD.NAME AS DESTINATION_NAME
    FROM [dbo].[REPORT_EXECUTION_SCHEDULE] RES
    INNER JOIN [dbo].[REPORT_ENTITIES] RE ON RES.ENT_ID = RE.ROW_ID
    INNER JOIN [dbo].[REPORTS] R ON RE.REPORT_ID = R.ROW_ID
    LEFT JOIN [dbo].[REPORT_DESTINATIONS] RD ON RES.REP_DEST_ID = RD.ROW_ID
    WHERE RES.TRAN_ID = @TranId
END
GO

-- Procedure to schedule a report
CREATE PROCEDURE [dbo].[ScheduleReport]
    @TranId NVARCHAR(50),
    @EntId NVARCHAR(15),
    @ExecConId NVARCHAR(15) = NULL,
    @RepDestId NVARCHAR(15) = NULL,
    @Format NVARCHAR(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    
    DECLARE @NewId NVARCHAR(15) = 'RES_' + FORMAT(GETDATE(), 'yyyyMMddHHmmss') + '_' + CAST(ABS(CHECKSUM(NEWID())) % 1000 AS NVARCHAR(3))
    
    INSERT INTO [dbo].[REPORT_EXECUTION_SCHEDULE] 
    ([ROW_ID], [TRAN_ID], [ENT_ID], [EXEC_CON_ID], [REP_DEST_ID], [FORMAT], [STATUS])
    VALUES 
    (@NewId, @TranId, @EntId, @ExecConId, @RepDestId, @Format, 'PENDING')
    
    SELECT @NewId AS SCHEDULE_ID
END
GO

-- =============================================
-- Views for Common Queries
-- =============================================

-- View for report execution details
CREATE VIEW [dbo].[ReportExecutionDetails] AS
SELECT 
    RES.ROW_ID AS SCHEDULE_ID,
    RES.TRAN_ID,
    RES.STATUS,
    RES.CREATED AS SCHEDULED_DATE,
    RES.LAST_UPD AS LAST_UPDATED,
    R.NAME AS REPORT_NAME,
    R.FILENAME AS REPORT_FILENAME,
    RD.NAME AS DESTINATION_NAME,
    RD.TYPE_CD AS DESTINATION_TYPE,
    C.FST_NAME + ' ' + C.LAST_NAME AS EXECUTED_BY,
    C.EMAIL_ADDR AS EXECUTOR_EMAIL
FROM [dbo].[REPORT_EXECUTION_SCHEDULE] RES
INNER JOIN [dbo].[REPORT_ENTITIES] RE ON RES.ENT_ID = RE.ROW_ID
INNER JOIN [dbo].[REPORTS] R ON RE.REPORT_ID = R.ROW_ID
LEFT JOIN [dbo].[REPORT_DESTINATIONS] RD ON RES.REP_DEST_ID = RD.ROW_ID
LEFT JOIN [dbo].[CONTACTS] C ON RES.EXEC_CON_ID = C.ROW_ID
GO

-- View for active reports
CREATE VIEW [dbo].[ActiveReports] AS
SELECT 
    R.ROW_ID,
    R.NAME,
    R.FILENAME,
    R.DESCRIPTION,
    COUNT(RE.ROW_ID) AS ENTITY_COUNT
FROM [dbo].[REPORTS] R
LEFT JOIN [dbo].[REPORT_ENTITIES] RE ON R.ROW_ID = RE.REPORT_ID
GROUP BY R.ROW_ID, R.NAME, R.FILENAME, R.DESCRIPTION
GO

-- =============================================
-- Security and Permissions
-- =============================================

-- Create database roles
CREATE ROLE [ReportReader]
GO
CREATE ROLE [ReportWriter]
GO
CREATE ROLE [ReportAdmin]
GO

-- Grant permissions to roles
GRANT SELECT ON [dbo].[REPORTS] TO [ReportReader]
GRANT SELECT ON [dbo].[REPORT_ENTITIES] TO [ReportReader]
GRANT SELECT ON [dbo].[REPORT_EXECUTION_SCHEDULE] TO [ReportReader]
GRANT SELECT ON [dbo].[REPORT_DESTINATIONS] TO [ReportReader]
GRANT SELECT ON [dbo].[CONTACTS] TO [ReportReader]
GRANT SELECT ON [dbo].[ORGANIZATIONS] TO [ReportReader]
GRANT SELECT ON [dbo].[SESSIONS] TO [ReportReader]
GRANT SELECT ON [dbo].[SESSION_PARTICIPANTS] TO [ReportReader]
GRANT SELECT ON [dbo].[LIST_OF_VALUES] TO [ReportReader]
GO

GRANT SELECT, INSERT, UPDATE ON [dbo].[REPORT_EXECUTION_SCHEDULE] TO [ReportWriter]
GRANT SELECT, INSERT, UPDATE ON [dbo].[PROCESSING_QUEUE] TO [ReportWriter]
GRANT SELECT, INSERT, UPDATE ON [dbo].[LETTER_HISTORY] TO [ReportWriter]
GO

GRANT ALL ON [dbo].[REPORTS] TO [ReportAdmin]
GRANT ALL ON [dbo].[REPORT_ENTITIES] TO [ReportAdmin]
GRANT ALL ON [dbo].[REPORT_DESTINATIONS] TO [ReportAdmin]
GRANT ALL ON [dbo].[CONTACTS] TO [ReportAdmin]
GRANT ALL ON [dbo].[ORGANIZATIONS] TO [ReportAdmin]
GRANT ALL ON [dbo].[SESSIONS] TO [ReportAdmin]
GRANT ALL ON [dbo].[SESSION_PARTICIPANTS] TO [ReportAdmin]
GRANT ALL ON [dbo].[LIST_OF_VALUES] TO [ReportAdmin]
GO

-- Grant execute permissions on stored procedures
GRANT EXECUTE ON [dbo].[GetReportStatus] TO [ReportReader]
GRANT EXECUTE ON [dbo].[ScheduleReport] TO [ReportWriter]
GO

PRINT 'Reporting Service Database Schema created successfully!'
PRINT 'Database: ReportingService'
PRINT 'Tables created: ' + CAST((SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE') AS NVARCHAR(10))
PRINT 'Stored procedures created: ' + CAST((SELECT COUNT(*) FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE') AS NVARCHAR(10))
PRINT 'Views created: ' + CAST((SELECT COUNT(*) FROM INFORMATION_SCHEMA.VIEWS) AS NVARCHAR(10))
